### PR TITLE
Project Completion

### PR DESCRIPTION
**Pull request by Aaron-RN**

### CODE REVIEW

**Review by bolah2009 — CHANGES_REQUESTED** [review]
Friendly reminder: You should use Github Flow in this project.
Please take a step back and watch video [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/).
Then create a brand new repo with correct setup and feature branch (with DESCRIPTIVE name) and copy your code there.

### This Code Review Request will be marked as invalid, so please submit a new one once you are ready!

### [Github Flow] 

* [ ] There is no `development` branch.
* [ ] Branches have the name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). We'll refer to it as a 'feature branch'.
* [ ] A Pull Request is made from “feature branch” into master branch and the `feature-branch` has some descriptive name.

#### :stop_sign:   This CRR is marked as invalid

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

**Comment by Aaron-RN** [comment]
> Friendly reminder: You should use Github Flow in this project.
> Please take a step back and watch video [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/).
> Then create a brand new repo with correct setup and feature branch (with DESCRIPTIVE name) and copy your code there.
> 
> ### This Code Review Request will be marked as invalid, so please submit a new one once you are ready!
> ### [Github Flow]
> * [ ]  There is no `development` branch.
> * [ ]  Branches have the name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). We'll refer to it as a 'feature branch'.
> * [ ]  A Pull Request is made from “feature branch” into master branch and the `feature-branch` has some descriptive name.
> 
> #### 🛑 This CRR is marked as invalid
> #### Feel free to reach me on slack if you having issues implementing these features. 👍
> Good luck with your next submission. 🌟
> 
> Cheers
> [Bola](https://bolabuari.com/)
> 
> ###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421589/

"Do not use the master branch for development. Create a development branch and set it as a default branch in your repository."

Also if you would look at the 10 or so closed pull requests you would see that I had a feature branch for each of the methods created... I simply merged them into development branch after I was done.

"Create a Pull Request from the feature-branch (give it a descriptive name that shortly says what this branch includes, e.g. homepage) branch to the development branch. We assume that this entire project is one feature for learning purposes."

Even though they said for 'learning purposes' use one feature branch I used one for each method and simply pulled and merged into development...

**Comment by maelfosso** [comment]
Here @Aaron-RN 

Thank you :smile: You wrote a very nice code.
But, there are lot of bug to fix

- [ ] **my_each** should returns an Enumerator if no block is given
     LocalJumpError:
       no block given (yield)
     # ./my_Enumerable.rb:5:in `block in my_each'
     # ./my_Enumerable.rb:4:in `each'
     # ./my_Enumerable.rb:4:in `my_each'

- [ ] **my_each_with_index** should returns an enumerator if no block is given

     LocalJumpError:
       no block given (yield)
     # ./my_Enumerable.rb:11:in `block in my_each_with_index'
     # ./my_Enumerable.rb:10:in `each'
     # ./my_Enumerable.rb:10:in `my_each_with_index'

- [ ] **my_select** should returns an enumerator if no block is given

     LocalJumpError:
       no block given (yield)
     # ./my_Enumerable.rb:18:in `block in my_select'
     # ./my_Enumerable.rb:5:in `block in my_each'
     # ./my_Enumerable.rb:4:in `each'
     # ./my_Enumerable.rb:4:in `my_each'
     # ./my_Enumerable.rb:17:in `my_select'

- [ ] **my_all?** when no block or argument is given should returns true when none of the collection members are false or nil
    
     LocalJumpError:
       no block given (yield)
     # ./my_Enumerable.rb:27:in `block in my_all?'
     # ./my_Enumerable.rb:5:in `block in my_each'
     # ./my_Enumerable.rb:4:in `each'
     # ./my_Enumerable.rb:4:in `my_each'
     # ./my_Enumerable.rb:26:in `my_all?'

- [ ]  **my_all?** when a class is passed as an argument returns true if all of the collection is a member of such class

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./my_Enumerable.rb:25:in `my_all?'

- [ ]  **my_all?** when a Regex is passed as an argument returns true if all of the collection matches the Regex
   
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./my_Enumerable.rb:25:in `my_all?'

- [ ]  **my_all?** when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./my_Enumerable.rb:25:in `my_all?'

- [ ]  **my_any?** when no block or argument is given  should returns true if at least one of the collection is not false or nil
     
     LocalJumpError:
       no block given (yield)
     # ./my_Enumerable.rb:36:in `block in my_any?'
     # ./my_Enumerable.rb:5:in `block in my_each'
     # ./my_Enumerable.rb:4:in `each'
     # ./my_Enumerable.rb:4:in `my_each'
     # ./my_Enumerable.rb:35:in `my_any?'

- [ ]  **my_any?** when a class is passed as an argument should returns true if at least one of the collection is a member of such class

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./my_Enumerable.rb:34:in `my_any?'


- [ ]  **my_any?** when a Regex is passed as an argument should returns false if none of the collection matches the Regex
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./my_Enumerable.rb:34:in `my_any?'

- [ ]  **my_any?** when a pattern other than Regex or a Class is given should returns false if none of the collection matches the pattern
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./my_Enumerable.rb:34:in `my_any?'

- [ ]  **my_none?** when no block or argument is given should returns true only if none of the collection members is true
      
      LocalJumpError:
        no block given (yield)
      # ./my_Enumerable.rb:45:in `block in my_none?'
      # ./my_Enumerable.rb:5:in `block in my_each'
      # ./my_Enumerable.rb:4:in `each'
      # ./my_Enumerable.rb:4:in `my_each'
      # ./my_Enumerable.rb:44:in `my_none?'

- [ ]  **my_none?** when a class is passed as an argument should returns true if none of the collection is a member of such class

      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./my_Enumerable.rb:43:in `my_none?'

- [ ]  **my_none?** when a Regex is passed as an argument should returns true only if none of the collection matches the Regex
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./my_Enumerable.rb:43:in `my_none?'

- [ ]  **my_none?** when a pattern other than Regex or a Class is given should returns true only if none of the collection matches the pattern
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./my_Enumerable.rb:43:in `my_none?'

- [ ]  **my_map** should returns an Enumerator if no block is given

      LocalJumpError:
        no block given (yield)
      # ./my_Enumerable.rb:79:in `block in my_map'
      # ./my_Enumerable.rb:5:in `block in my_each'
      # ./my_Enumerable.rb:4:in `each'
      # ./my_Enumerable.rb:4:in `my_each'
      # ./my_Enumerable.rb:75:in `my_map'

- [ ]  **my_inject** combines all elements of enum by applying a binary operation, specified by a block

      NoMethodError:
      # ./my_Enumerable.rb:10:in `my_each_with_index'
      # ./my_Enumerable.rb:87:in `my_inject'

- [ ]  **my_inject**  when a symbol is specified combines each element of the collection by applying the symbol as a named method

      ArgumentError:
        wrong number of arguments (given 2, expected 0..1)
      # ./my_Enumerable.rb:85:in `my_inject'

Kindly make those changes following the indications.
Then submit a new code review request.
Thanks

**Review by maelfosso — CHANGES_REQUESTED** [review]
Here @Aaron-RN 

Thank you :smile: You wrote a very nice code.
But, there are lot of bug to fix

- [x] **my_each** should returns an Enumerator if no block is given
     LocalJumpError:
       no block given (yield)
     # ./my_Enumerable.rb:5:in `block in my_each'
     # ./my_Enumerable.rb:4:in `each'
     # ./my_Enumerable.rb:4:in `my_each'

- [x] **my_each_with_index** should returns an enumerator if no block is given

     LocalJumpError:
       no block given (yield)
     # ./my_Enumerable.rb:11:in `block in my_each_with_index'
     # ./my_Enumerable.rb:10:in `each'
     # ./my_Enumerable.rb:10:in `my_each_with_index'

- [x] **my_select** should returns an enumerator if no block is given

     LocalJumpError:
       no block given (yield)
     # ./my_Enumerable.rb:18:in `block in my_select'
     # ./my_Enumerable.rb:5:in `block in my_each'
     # ./my_Enumerable.rb:4:in `each'
     # ./my_Enumerable.rb:4:in `my_each'
     # ./my_Enumerable.rb:17:in `my_select'

- [x] **my_all?** when no block or argument is given should returns true when none of the collection members are false or nil
    
     LocalJumpError:
       no block given (yield)
     # ./my_Enumerable.rb:27:in `block in my_all?'
     # ./my_Enumerable.rb:5:in `block in my_each'
     # ./my_Enumerable.rb:4:in `each'
     # ./my_Enumerable.rb:4:in `my_each'
     # ./my_Enumerable.rb:26:in `my_all?'

- [x]  **my_all?** when a class is passed as an argument returns true if all of the collection is a member of such class

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./my_Enumerable.rb:25:in `my_all?'

- [x]  **my_all?** when a Regex is passed as an argument returns true if all of the collection matches the Regex
   
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./my_Enumerable.rb:25:in `my_all?'

- [x]  **my_all?** when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./my_Enumerable.rb:25:in `my_all?'

- [x]  **my_any?** when no block or argument is given  should returns true if at least one of the collection is not false or nil
     
     LocalJumpError:
       no block given (yield)
     # ./my_Enumerable.rb:36:in `block in my_any?'
     # ./my_Enumerable.rb:5:in `block in my_each'
     # ./my_Enumerable.rb:4:in `each'
     # ./my_Enumerable.rb:4:in `my_each'
     # ./my_Enumerable.rb:35:in `my_any?'

- [x]  **my_any?** when a class is passed as an argument should returns true if at least one of the collection is a member of such class

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./my_Enumerable.rb:34:in `my_any?'


- [x]  **my_any?** when a Regex is passed as an argument should returns false if none of the collection matches the Regex
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./my_Enumerable.rb:34:in `my_any?'

- [x]  **my_any?** when a pattern other than Regex or a Class is given should returns false if none of the collection matches the pattern
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./my_Enumerable.rb:34:in `my_any?'

- [x]  **my_none?** when no block or argument is given should returns true only if none of the collection members is true
      
      LocalJumpError:
        no block given (yield)
      # ./my_Enumerable.rb:45:in `block in my_none?'
      # ./my_Enumerable.rb:5:in `block in my_each'
      # ./my_Enumerable.rb:4:in `each'
      # ./my_Enumerable.rb:4:in `my_each'
      # ./my_Enumerable.rb:44:in `my_none?'

- [x]  **my_none?** when a class is passed as an argument should returns true if none of the collection is a member of such class

      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./my_Enumerable.rb:43:in `my_none?'

- [x]  **my_none?** when a Regex is passed as an argument should returns true only if none of the collection matches the Regex
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./my_Enumerable.rb:43:in `my_none?'

- [x]  **my_none?** when a pattern other than Regex or a Class is given should returns true only if none of the collection matches the pattern
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
      # ./my_Enumerable.rb:43:in `my_none?'

- [x]  **my_map** should returns an Enumerator if no block is given

      LocalJumpError:
        no block given (yield)
      # ./my_Enumerable.rb:79:in `block in my_map'
      # ./my_Enumerable.rb:5:in `block in my_each'
      # ./my_Enumerable.rb:4:in `each'
      # ./my_Enumerable.rb:4:in `my_each'
      # ./my_Enumerable.rb:75:in `my_map'

- [x]  **my_inject** combines all elements of enum by applying a binary operation, specified by a block

      NoMethodError:
      # ./my_Enumerable.rb:10:in `my_each_with_index'
      # ./my_Enumerable.rb:87:in `my_inject'

- [x]  **my_inject**  when a symbol is specified combines each element of the collection by applying the symbol as a named method

      ArgumentError:
        wrong number of arguments (given 2, expected 0..1)
      # ./my_Enumerable.rb:85:in `my_inject'

Kindly make those changes following the indications.
Then submit a new code review request.
Thanks

**Comment by bolah2009** [comment]
> Also if you would look at the 10 or so closed pull requests you would see that I had a feature branch for each of the methods created... I simply merged them into development branch after I was done.

> Even though they said for 'learning purposes' use one feature branch I used one for each method and simply pulled and merged into development...

### This project should use [**Git flow**](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/)
So my point is:
- set `development` as the default branch. Do not use the `master` branch.
- your pull request should be from the `feature-branch` branch into the `development` branch. no `master` branch

I hope this is clear since @maelfosso have started a review please take note for future projects.


> Follow the [Git Flow guidelines](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/).
> - Do not use the master branch for development. Create a development branch and set it as a default branch in your repository.
> - Do not work directly in the development branch. Create a feature-branch branch (give it a descriptive name) based on the development branch for the feature you implement (we assume that this entire project is one feature for learning purposes.) and open a Pull Request from it. When your feature is ready and Pull request approved, you can merge it to the development branch.
> Commit changes often.


-----

### This is not a CRR

**Pull request closed without merging**
